### ISSUE TITLE
dvisvgm backend: issues with beamer standard animations/transitions (\pause)

### ISSUE THREAD

**Issue by emilioj** [josephwright/beamer#591]
Hi!
I am trying to translate some PDf slides (LaTeX beamer) to svg to get advantage of the \animate package without needing a non-free PDF viewer. However, I am having some issues with standard beamer animations when using the `dvisvgm` backend, in different scenarios.
This is a simple example that does not work as expected when generating the SVG:

```
\documentclass[dvisvgm,aspectratio=169]{beamer}
\setbeamertemplate{navigation symbols}{}

\begin{document}

\begin{frame}
  \begin{itemize}
  \item 1
    \pause

  \item 2
    \pause

  \item 3
    \begin{block}{foo bar}
      foo bar
    \end{block}
  \end{itemize}
\end{frame}

\end{document}
```

After `latex example.tex; latex example.tex; dvisvgm --font-format=woff --zoom=-1 -p1,- example.dvi` three SVG files are generated, but the beamer block is visible in all of them instead of only in the last one.

I am using **LaTeX-2020** and **dvisvgm 2.9.1**

Regards,
E

**Comment by samcarter** [comment]
Seems something changed with TL2020, with TL2019 it works fine.

Converting the dvi file produced with latex 2019 with dvisvgm from 2020 also gives this problem. So a dvisvgm problem?

**Comment by emilioj** [comment]
Hi!

> Seems something changed with TL2020, with TL2019 it works fine.

Hmmmm... I was using TL2019 until some days ago, but I need some features from the `animate` package that only work in TL2020 [1]. Once I managed to have my animated figures Ok I bumped this unexpected problem with standard beamer animations :-/

> Converting the dvi file produced with latex 2019 with dvisvgm from 2020 also gives this problem. So a dvisvgm problem?

You mean TL2019+dvisvgm2.9 work Ok but TL2019+dvisvgm2.9.1 does not?

According to dvisvgm developer (I filed an issue there earlier to come here) it seems a problem with beamer dvisvgm backend, since it works flawlessly with other backends+dvisvgm to generate the SVG output.

Regards

[1] https://tex.stackexchange.com/questions/537424/problems-to-get-animategraphics-from-animate-package-working-properly-in-beamer

**Comment by samcarter** [comment]
If I start from this dvi file: 
[document.zip](https://github.com/josephwright/beamer/files/4475057/document.zip)
 I get the correct result with dvisvgm 2.6.3 (TL19), but with dvisvgm 2.9.1 (TL20) I can reproduce the error (I don't have dvisvgm2.9.)

**Comment by louisstuart96** [comment]
Try `\documentclass[pgf=dvisvgm, ...]`?

This option sets backend of `pgf` to `dvisvgm`, but the underneath graphics driver remains `dvips`. Seems to solve the problem in MWE (temporarily, maybe).

**Comment by emilioj** [comment]
Hi!

> Try `\documentclass[pgf=dvisvgm, ...]`?
> 
> This option sets backend of `pgf` to `dvisvgm`, but the underneath graphics driver remains `dvips`. 

Ok, using `\documentclass[pgf=dvisvgm, ...]` instead of `\documentclass[dvisvgm, ...]` does the trick for the "standard" beamer animation (now my previous example runs ok), but I want to use the `animate` package as well and it does not work with that change.
A mean this: (just adding a slide with an animation based on EPS files in my previous example)

```
\documentclass[dvisvgm,aspectratio=169]{beamer}
\setbeamertemplate{navigation symbols}{}

\usepackage{animate}

\begin{document}

\begin{frame}{Simple raycasting animation}
    \animategraphics[controls,loop,autoplay]{16}{tmp/raycasting_frame}{00}{39}
\end{frame}

\begin{frame}
  \begin{itemize}
  \item 1
    \pause

  \item 2
    \pause

  \item 3
    \begin{block}{foo bar}
      foo bar
    \end{block}
  \end{itemize}
\end{frame}

\end{document}
```
With `\documentclass[dvisvgm, ...]` I get the weird behavior with the standard beamer animation whereas ` \animategraphics` works ok, but with `\documentclass[pgf=dvisvgm, ...]` is the other way around.

My animation is just a bunch of EPS files obtained by:
```
convert -coalesce Simple_raycasting_with_fisheye_correction.gif raycasting_frame%02d.eps
```
from this animated GIF: https://upload.wikimedia.org/wikipedia/commons/e/e7/Simple_raycasting_with_fisheye_correction.gif

**Comment by louisstuart96** [comment]
In the SVG files the overlay behavior of list items are correct (covered by `<g visibility="hidden">`), but the entire block is not covered. Not sure whether it is `pgf` or the driver to blame; the code for overlay control has been unchanged in `beamer`.

@samcarter You may check the SVG files generated by older version of `dvisvgm` .

**Comment by agrahn** [comment]
In Nov 19, Martin (@mgieseki) implemented the PS `nulldevice` operator in `dvisvgm`:

```
commit 67bf043bf77205557370d2e29e29067938925f9a
Author: Martin Gieseking <martin.gieseking@uos.de>
Date:   Tue Nov 5 19:58:53 2019 +0100

    added support for PS operator 'nulldevice'
```
This invalidates / makes redundant the current low-level implementation of the beamer-pause code in the `dvisvgm` driver of PGF.

The code example below fixes this. I am going to prepare a pull-request for PGF (@hmenke).

Typeset with
````
latex example
latex example
dvisvgm --font-format=woff --zoom=-1 -p1,- example
````

```latex
\documentclass[dvisvgm,aspectratio=169]{beamer}
\setbeamertemplate{navigation symbols}{}

\makeatletter
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% in pgf.git/tex/generic/pgf/systemlayer/pgfsys-common-svg.def
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% replace

%% Invisibility
%\def\pgfsys@begininvisible{\pgfsysprotocol@literal{<g visibility="hidden">\pgfsys@svg@newline }}
%\def\pgfsys@endinvisible{\pgfsysprotocol@literal{</g>}}
%\def\pgfsys@begininvisiblescope{\pgfsys@beginscope@{ visibility="hidden"}}
%\def\pgfsys@endinvisiblescope{\pgfsys@endscope}

% with (similar to pgf.git/tex/generic/pgf/systemlayer/pgfsys-dvips.def)

\def\pgfsys@begininvisible{%
  \special{ps::[begin]}%
  \special{ps:: gsave nulldevice}%
  \special{ps::[end]}}
\def\pgfsys@endinvisible{%
  \special{ps::[begin]}%
  \special{ps:: grestore}%
  \special{ps::[end]}%
}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% from pgf.git/tex/generic/pgf/systemlayer/pgfsys.code.tex)
% to override current definition in pgfsys-common-svg.def

\def\pgfsys@begininvisiblescope{\pgfsys@beginscope\pgfsys@begininvisible}
% Works like pgfsys@begininvisible, but it may open a graphics scope.

\def\pgfsys@endinvisiblescope{\pgfsys@endinvisible\pgfsys@endscope}
% Closes the invisibility scope.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\makeatother
\begin{document}

\begin{frame}
  \begin{itemize}
  \item 1
    \pause

  \item 2
    \pause

  \item 3
    \begin{block}{foo bar}
      foo bar
    \end{block}
  \end{itemize}
\end{frame}

\end{document}
```

![beamer-pause](https://user-images.githubusercontent.com/832385/81947560-fef72e80-9600-11ea-8043-5c707bf7f911.gif)

**Comment by agrahn** [comment]
I have just found that this breaks visibility of TikZ graphics on layered slides (if TikZ loads its SVG driver on the system level). Sorry.

For now, I suggest to let TikZ use the dvips driver for the drawing routines, as `dvisvgm` gracefully converts PostScript to SVG. Therefore, don't set `dvisvgm` globally, but as a package option only (for `animate`):

```latex
\documentclass[aspectratio=169]{beamer}
\setbeamertemplate{navigation symbols}{}

\usepackage{tikz}
\usepackage[dvisvgm]{animate}

\begin{document}

%\begin{frame}{Simple raycasting animation}
%    \animategraphics[controls,loop,autoplay]{16}{tmp/raycasting_frame}{00}{39}
%\end{frame}

\begin{frame}
  \begin{itemize}
  \item 1
    \pause

  \item 2
    \pause

  \item 3
    \begin{block}{foo bar}
      foo bar
    \end{block}
    \pause

  \item TikZ code:\\
    \tikz \draw (0,0) rectangle (1,1);
  \end{itemize}
\end{frame}

\end{document}
```

**Comment by mgieseki** [comment]
> If I start from this dvi file:
> [document.zip](https://github.com/josephwright/beamer/files/4475057/document.zip)
> I get the correct result with dvisvgm 2.6.3 (TL19), but with dvisvgm 2.9.1 (TL20) I can reproduce the error (I don't have dvisvgm2.9.)

I just noticed this ticket since Alex pinged me above. So, this comment might already be outdated. Nonetheless, just a quick note for the record. :-)
I doubt dvisvgm 2.6.3 creates proper SVG files from the attached DVI. The results should be similar to those of dvisvgm 2.9.1. I haven't tested it, though. However, the DVI contains empty SVG groups which are probably supposed to enclose the hidden text, but they don't. Here's an excerpt from the `dviasm` output of the first page. The `foo bar`s are not wrapped by the "hidden" groups and are therefore visible. This must be a `beamer`/`TikZ` issue.
```
 push:
  xxx: 'color push rgb 0.2 0.2 0.7'
  push:
    push:
     fnt: cmss12 at 12pt
     set: 'fo'
     right: 0.326385pt
     set: 'o'
     right: 3.916626pt
     set: 'ba'
     right: -0.326385pt
     set: 'r'
    pop:
  pop:
  right: 398.338593pt
  xxx: 'color pop'
 pop:
 down: 13.600006pt
 push:
  xxx: 'color push gray 0'
  push:
    push:
     fnt: cmss10 (10pt) at 10.949997pt
     set: 'fo'
     right: 0.304169pt
     set: 'o'
     right: 3.649994pt
     set: 'ba'
     right: -0.304184pt
     set: 'r'
    pop:
  pop:
  right: 398.338593pt
  xxx: 'color pop'
 pop:
 xxx: 'dvisvgm:raw <g visibility="hidden">{?nl} '
 xxx: 'dvisvgm:raw </g> '
 xxx: 'dvisvgm:raw <g visibility="hidden">{?nl} '
 xxx: 'dvisvgm:raw </g> '
 xxx: 'dvisvgm:raw <g visibility="hidden">{?nl} '
 xxx: 'dvisvgm:raw </g> '
 xxx: 'color pop'
 xxx: 'dvisvgm:raw <g visibility="hidden">{?nl} '
 xxx: 'dvisvgm:raw </g> '
 xxx: 'dvisvgm:raw <g visibility="hidden">{?nl} '
 xxx: 'dvisvgm:raw </g> '
 xxx: 'dvisvgm:raw <g visibility="hidden">{?nl} '
 xxx: 'dvisvgm:raw </g> '
 xxx: 'dvisvgm:raw </g> '
 xxx: 'dvisvgm:raw <g visibility="hidden">{?nl} '
 xxx: 'dvisvgm:raw </g> '
```
